import Groq from "groq-sdk";
import { GoogleGenAI } from "@google/genai";

let groq: Groq | null = null;
let aiClient: GoogleGenAI | null = null;

export function getGroqClient(): Groq | null {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    console.warn("GROQ_API_KEY is missing. Falling back to platform native Gemini API.");
    return null;
  }
  if (!groq) {
    groq = new Groq({ apiKey });
  }
  return groq;
}

export function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiClient;
}

/**
 * Executes a generateContent call with automatic exponential backoff retry on transient errors
 * and failover to alternative models should the primary model stay unavailable.
 */
async function generateContentWithRetry(ai: GoogleGenAI, params: any, maxRetries = 3): Promise<any> {
  const modelsToTry = [
    params.model || "gemini-3.5-flash",
    "gemini-flash-latest",
    "gemini-3.1-flash-lite"
  ];

  let lastError: any = null;

  for (const model of modelsToTry) {
    let attempt = 0;
    while (attempt < maxRetries) {
      try {
        console.log(`CompassIQ: Generating content with model: ${model} (attempt ${attempt + 1}/${maxRetries})`);
        const response = await ai.models.generateContent({
          ...params,
          model: model
        });
        return response;
      } catch (err: any) {
        attempt++;
        lastError = err;
        const errMsg = err?.message || String(err);
        const isTransient = 
          errMsg.includes("503") || 
          errMsg.includes("UNAVAILABLE") || 
          errMsg.includes("high demand") || 
          errMsg.includes("429") || 
          errMsg.includes("RESOURCE_EXHAUSTED") ||
          err?.status === 503 ||
          err?.status === 429;

        if (isTransient && attempt < maxRetries) {
          const delay = Math.pow(2, attempt) * 500; // 500ms, 1000ms, 2000ms
          console.warn(`CompassIQ: Transient error generated by Gemini client on model ${model}: ${errMsg}. Retrying in ${delay}ms...`);
          await new Promise(resolve => setTimeout(resolve, delay));
        } else {
          console.error(`CompassIQ: Error on model ${model}:`, errMsg);
          break; // Stop retrying this model, fallback to the next model in the list
        }
      }
    }
  }

  throw lastError || new Error("CompassIQ GenAI: All tried models failed or were unavailable.");
}

async function callGemini(systemPrompt: string, userMessage: string, history: any[] = []): Promise<string> {
  console.log("CompassIQ: Using platform-native Gemini API for expert grounded analysis.");
  const ai = getGeminiClient();

  const contents: any[] = [];
  if (history && history.length > 0) {
    for (const item of history) {
      if (item.content) {
        contents.push({
          role: item.role === "user" ? "user" : "model",
          parts: [{ text: item.content }]
        });
      }
    }
  }

  const lastItem = contents[contents.length - 1];
  if (userMessage && (!lastItem || lastItem.parts[0]?.text !== userMessage || lastItem.role !== "user")) {
    contents.push({
      role: "user",
      parts: [{ text: userMessage }]
    });
  }

  const response = await generateContentWithRetry(ai, {
    contents,
    config: {
      systemInstruction: systemPrompt,
      temperature: 0.1,
    }
  });

  const responseText = response.text;
  if (responseText) {
    console.log("CompassIQ: Gemini response generated successfully.");
    return responseText;
  }
  throw new Error("Received empty response from Gemini.");
}

/**
 * Call Gemini or Groq chat completions with zero-setup fallback.
 */
export async function callGroq(systemPrompt: string, userMessage: string, history: any[] = []): Promise<string> {
  const groqApiKey = process.env.GROQ_API_KEY;
  const geminiApiKey = process.env.GEMINI_API_KEY;

  if (!groqApiKey && !geminiApiKey) {
    throw new Error("Missing AI credentials: set GROQ_API_KEY or GEMINI_API_KEY in .env.local");
  }

  if (!groqApiKey) {
    try {
      return await callGemini(systemPrompt, userMessage, history);
    } catch (geminiError: any) {
      console.error("CompassIQ error utilizing Gemini client:", geminiError);
      throw geminiError;
    }
  }

  // Legacy Groq path
  const client = getGroqClient();
  if (!client) {
    throw new Error("Unable to initialize Groq API client.");
  }

  const messages: { role: "system" | "user" | "assistant"; content: string }[] = [
    { role: "system", content: systemPrompt }
  ];

  if (history && history.length > 0) {
    for (const item of history) {
      if (item.content) {
        messages.push({
          role: item.role === "user" ? "user" : "assistant",
          content: item.content
        });
      }
    }
  }

  const lastItem = messages[messages.length - 1];
  if (userMessage && (!lastItem || lastItem.content !== userMessage || lastItem.role !== "user")) {
    messages.push({ role: "user", content: userMessage });
  }

  const models = [
    "openai/gpt-oss-120b",
    "llama-3.3-70b-versatile",
    "llama-3.1-70b-versatile",
    "llama3-8b-8192",
    "mixtral-8x7b-32768",
    "gemma2-9b-it"
  ];

  let lastError: any = null;

  for (const modelName of models) {
    try {
      console.log(`CompassIQ: Directing prompt to Groq model: ${modelName}`);
      const completion = await client.chat.completions.create({
        model: modelName,
        messages: messages,
        temperature: 0.1,
        max_tokens: 2048
      });
      const responseText = completion.choices[0]?.message?.content;
      if (responseText) {
        console.log(`CompassIQ: Groq API response successfully generated using ${modelName}`);
        return responseText;
      }
    } catch (err: any) {
      lastError = err;
      console.warn(`CompassIQ Groq Error: Model ${modelName} failed or unavailable. attempting fallback. Detail: ${err.message}`);
    }
  }

  if (geminiApiKey) {
    console.warn("CompassIQ: All Groq models failed. Falling back to Gemini.");
    try {
      return await callGemini(systemPrompt, userMessage, history);
    } catch (geminiError: any) {
      console.error("CompassIQ: Gemini fallback also failed:", geminiError);
      throw geminiError;
    }
  }

  throw new Error(`CompassIQ: All Groq models failed. Last error: ${lastError?.message || lastError}`);
}
